export const packages = [
  { id: 1, name: "Menu Cars", price: 15.00, category: "Menu", description: "Access to the exclusive vehicles menu." },
  { id: 2, name: "Menu Clothes", price: 10.00, category: "Menu", description: "Custom clothing options menu." },
  { id: 3, name: "private CAR", price: 25.00, category: "Vehicles", description: "Your own 1-of-1 private vehicle." },
  { id: 4, name: "Elite Pack", price: 50.00, category: "Bundles", description: "The ultimate starter bundle for elite players." },
  { id: 5, name: "SPECIAL ID", price: 100.00, category: "ID", description: "Custom low-digit server ID." },
  { id: 6, name: "Elite Pets", price: 20.00, category: "Pets", description: "Exclusive in-game companions." },
  { id: 7, name: "Baby Pack", price: 15.00, category: "Bundles", description: "Starter items to get you going." },
  { id: 8, name: "Anime", price: 10.00, category: "Misc", description: "Anime themed items and props." },
  { id: 9, name: "CAVE", price: 30.00, category: "Misc", description: "Private cave hideout access." },
  { id: 10, name: "Private Home", price: 45.00, category: "Housing", description: "Custom mapping interior." },
  { id: 11, name: "Cinema Remote", price: 5.00, category: "Misc", description: "Control the drive-in cinema." },
  { id: 12, name: "JUST NAME", price: 10.00, category: "Role", description: "Custom colored name overhead." },
  { id: 13, name: "ONLY NAME", price: 10.00, category: "Role", description: "Hide your ID, show only name." },
  { id: 14, name: "ID NAME", price: 15.00, category: "Role", description: "Custom tag formatting." },
  { id: 15, name: "BATMAN", price: 20.00, category: "Heroes", description: "Play as the Dark Knight." },
  { id: 16, name: "IRON MAN", price: 20.00, category: "Heroes", description: "Full suit and abilities." },
  { id: 17, name: "HULK", price: 20.00, category: "Heroes", description: "Smash through the city." },
  { id: 18, name: "SUPERMAN", price: 20.00, category: "Heroes", description: "Flight and super strength." },
  { id: 19, name: "SPIDER MAN", price: 20.00, category: "Heroes", description: "Web swinging enabled." },
  { id: 20, name: "HITMAN", price: 15.00, category: "Heroes", description: "Agent 47 custom ped." },
  { id: 21, name: "Catwomen", price: 15.00, category: "Heroes", description: "Custom ped and agility." },
  { id: 22, name: "SLENDAR MAN", price: 15.00, category: "Heroes", description: "Terrorize the server." },
  { id: 23, name: "Flash", price: 15.00, category: "Heroes", description: "Super speed abilities." },
  { id: 24, name: "JOKER", price: 15.00, category: "Heroes", description: "Custom ped and laugh." },
  { id: 25, name: "Kill Field", price: 10.00, category: "Misc", description: "Custom kill effects." },
  { id: 26, name: "Login", price: 5.00, category: "Misc", description: "Custom login screen music/video." },
  { id: 27, name: "GHOST", price: 15.00, category: "Misc", description: "Ghost ped model." },
  { id: 28, name: "Do Not Disturb", price: 5.00, category: "Misc", description: "Ignore all requests." },
  { id: 29, name: "Red Ruby", price: 50.00, category: "Misc", description: "Premium red ruby tier." },
  { id: 30, name: "كبار داعمين السيرفر", price: 200.00, category: "VIP", description: "Top Supporter rank with exclusive perks." },
  { id: 31, name: "Kill Field List", price: 15.00, category: "Misc", description: "Custom killfeed UI." },
  { id: 32, name: "Chat Name", price: 10.00, category: "Role", description: "Colored chat name." },
  { id: 33, name: "MASTER", price: 75.00, category: "VIP", description: "Master VIP Tier." },
  { id: 34, name: "DIAMOND", price: 50.00, category: "VIP", description: "Diamond VIP Tier." },
  { id: 35, name: "GOLD", price: 30.00, category: "VIP", description: "Gold VIP Tier." },
  { id: 36, name: "SILVER", price: 15.00, category: "VIP", description: "Silver VIP Tier." },
  { id: 37, name: "VIP MENU", price: 40.00, category: "VIP", description: "Access to VIP exclusive menu." },
];

export type Package = typeof packages[0];
