export const packages = [
  { id: 1, name: "GHOST", price: 400.00, category: "VIP", description: "Premium Ghost status. First purchase." },
  { id: 2, name: "Do Not Disturb", price: 400.00, category: "Premium", description: "Stay invisible and ignore all requests." },
  { id: 3, name: "SPECIAL ID - Premium 2-digit", price: 185.00, category: "ID", description: "Premium 2-digit server ID (e.g. 55, 66)." },
  { id: 4, name: "Red Ruby", price: 200.00, category: "VIP", description: "Premium ruby tier membership." },
  { id: 5, name: "SPECIAL ID - Normal 2-digit", price: 150.00, category: "ID", description: "Standard 2-digit server ID (e.g. 40, 30)." },
  { id: 6, name: "CAVE (1 Month)", price: 150.00, category: "Housing", description: "Private cave hideout for 1 month." },
  { id: 7, name: "CAVE (1 Week)", price: 80.00, category: "Housing", description: "Private cave hideout for 1 week." },
  { id: 8, name: "SPECIAL ID - Repeated 3-digit", price: 80.00, category: "ID", description: "Premium repeated 3-digit ID (e.g. 111, 333)." },
  { id: 9, name: "Kill Field List", price: 80.00, category: "Misc", description: "Custom killfeed UI." },
  { id: 10, name: "SPECIAL ID - 6-Digit Negative Repeating", price: 70.00, category: "ID", description: "6-Digit negative repeating (e.g. -222222, -333333)." },
  { id: 11, name: "VIP MENU", price: 70.00, category: "VIP", description: "Access to VIP exclusive menu." },
  { id: 12, name: "MASTER", price: 70.00, category: "VIP", description: "Master VIP Tier - Ultimate status." },
  { id: 13, name: "SPECIAL ID - Repeated 4-digit", price: 70.00, category: "ID", description: "Premium 4-digit repeated ID (e.g. 1111, 3333)." },
  { id: 14, name: "SPECIAL ID - Premium Triplet", price: 65.00, category: "ID", description: "Premium 3-digit server ID (e.g. 112, 312)." },
  { id: 15, name: "SPECIAL ID - 6-Digit Negative Standard", price: 65.00, category: "ID", description: "6-Digit negative standard (e.g. -656565)." },
  { id: 16, name: "كبار داعمين السيرفر", price: 128.00, category: "VIP", description: "Top Supporter rank with exclusive perks." },
  { id: 17, name: "DIAMOND", price: 44.00, category: "VIP", description: "Diamond VIP Tier." },
  { id: 18, name: "GOLD", price: 36.00, category: "VIP", description: "Gold VIP Tier." },
  { id: 19, name: "SILVER", price: 30.00, category: "VIP", description: "Silver VIP Tier." },
  { id: 20, name: "Menu Cars", price: 30.00, category: "Menu", description: "Access to the exclusive vehicles menu." },
  { id: 21, name: "Menu Clothes", price: 30.00, category: "Menu", description: "Custom clothing options menu." },
  { id: 22, name: "Elite Pack", price: 50.00, category: "Bundles", description: "The ultimate starter bundle for elite players." },
  { id: 23, name: "Elite Pets", price: 50.00, category: "Pets", description: "Exclusive in-game companions." },
  { id: 24, name: "Cinema Remote", price: 50.00, category: "Misc", description: "Control the drive-in cinema." },
  { id: 25, name: "Baby Pack", price: 40.00, category: "Bundles", description: "Starter items to get you going." },
  { id: 26, name: "ONLY NAME", price: 40.00, category: "Role", description: "Hide your ID, show only name." },
  { id: 27, name: "SPECIAL ID - Standard Triplet", price: 55.00, category: "ID", description: "Standard 3-digit server ID (e.g. 136, 362)." },
  { id: 28, name: "SPECIAL ID - 5-Digit Negative", price: 55.00, category: "ID", description: "5-Digit negative ID (minimum 5 digits, e.g. -52133)." },
  { id: 29, name: "CAVE (2 Days)", price: 30.00, category: "Housing", description: "Private cave hideout for 2 days." },
  { id: 30, name: "JUST NAME", price: 200.00, category: "Role", description: "Custom colored name overhead tag." },
  { id: 31, name: "BATMAN", price: 20.00, category: "Heroes", description: "Play as the Dark Knight." },
  { id: 32, name: "IRON MAN", price: 20.00, category: "Heroes", description: "Full suit and abilities." },
  { id: 33, name: "HULK", price: 20.00, category: "Heroes", description: "Smash through the city." },
  { id: 34, name: "SUPERMAN", price: 20.00, category: "Heroes", description: "Flight and super strength." },
  { id: 35, name: "SPIDER MAN", price: 20.00, category: "Heroes", description: "Web swinging enabled." },
  { id: 36, name: "HITMAN", price: 20.00, category: "Heroes", description: "Agent 47 custom ped." },
  { id: 37, name: "Catwomen", price: 20.00, category: "Heroes", description: "Custom ped and agility." },
  { id: 38, name: "SLENDAR MAN", price: 20.00, category: "Heroes", description: "Terrorize the server." },
  { id: 39, name: "Flash", price: 20.00, category: "Heroes", description: "Super speed abilities." },
  { id: 40, name: "JOKER", price: 20.00, category: "Heroes", description: "Custom ped and laugh." },
  { id: 41, name: "Kill Field", price: 20.00, category: "Misc", description: "Custom kill effects." },
  { id: 42, name: "ID NAME", price: 25.00, category: "Role", description: "Custom tag formatting." },
];

export type Package = typeof packages[0];
